202306-NEA-DZ-FEW/team-five

- .github/workflows/issue-autolink.yml
- .prettierignore
- README.md
- package-lock.json
> 1 setup repositorys

- package-lock.json
- package.json
- src/pages/_app.jsx
- src/redux/shopperSlice.js
- src/redux/store.jsx
This issue encompasses multiple tasks related to setting up Redux for state management, implementing Redux actions and reducers, and integrating Redux Persist.
Closes #12
- Resolve #12
> feat(redux): redux State Management Setup

- src/Utils/firebase.js
setting up Firebase, integrating user authentication, and configuring Firestore and env file
Closes #11
- Resolve #11
> feat(firebase): firebase Setup & Configuration

- .prettierignore
- package-lock.json
- package.json
- postcss.config.js
- src/styles/globals.css
- tailwind.config.js
This issue is focused on integrating Tilwind into our project and defining the project structure for improved development efficiency and maintainability.
Closes #20
- Resolve #20
> style(tailwind): integrate Tilwind

- public/locales/ar/signup.json
- public/locales/en/signup.json
- src/components/Auth/Signin/index.jsx
- src/components/Auth/Signup/index.jsx
- src/pages/auth/index.js
This sign-in page will allow existing users to log in to their accounts.
Closes #26
- Resolve #26
> feat(signin): create sign In component

- package-lock.json
- package.json
- src/components/Admin/Chart.jsx
- src/containers/Admin/CouponUsed/index.jsx
- src/pages/admin/index.js
- src/pages/auth/index.js
Design and implement a chart component that visually represents the usage of coupons in our system.
Closes #31
- Resolve #31
> feat(chart couponused admin): design and implement a chart component

- src/pages/auth/FormatePrice.jsx
Develop a FormatPrice that formats and displays prices according to the specified format or currency.
Closes #65
- Resolve #65
> feat(formateprice): create FormatPrice

- src/components/Cards/CouponCard/index.jsx
Design and implement a "CouponCard" component that displays information about coupons
Closes #66
- Resolve #66
> feat(couponcard): create CouponCard

- src/components/Cards/CheckoutCard/index.jsx
Design and implement a "CheckoutCard" component that allows users to review and confirm their selected items
Closes #68
- Resolve #68
> feat(checkoutcard): create CheckoutCard Component

- src/containers/Cart/Cartpage/index.jsx
Design and implement a "Cart Container" component that serves as a container for managing and displaying the user's shopping cart contents.
Closes #71
- Resolve #71
> feat(cartpage container): create Cart Container

- src/components/Cards/CouponCard/index.jsx
- src/components/CouponsCard/Coupons.jsx
- src/pages/Coupons/index.jsx
- src/pages/cart/index.js
- src/redux/shopperSlice.js
integrating Firebase for data storage and management and using Redux for state management.
Closes #74
- Resolve #74
> feat(couponpage redux): firebase and Redux Functionality for Coupon Page

- src/components/CouponsCard/Coupons.jsx
this PR will tackle the problem of the vercel deployment.
- Resolve #93
> fix: rewrite the code so the verscel deploy

- jest.config.js
- package-lock.json
- package.json
- src/__mocks__/next/router.js
Configure Jest to use mocks for testing in the project
Closes #122
- Resolve #122
> feat(mocks): setup jest mocks test

- src/containers/Blogcontainer/__test__/Blogcontainer.test.js
- src/containers/Blogcontainer/__test__/__snapshots__/Blogcontainer.test.js.snap
> test(blogcontainer test): creating Blogcontainer test

- src/components/Cards/CheckoutCard/index.jsx
> feat(checkoutcard): generate Random Coupon Number and Add to Firebase

- src/components/Cards/AdminCoupon/index.jsx
Design and implement a coupon card component specifically for the admin dashboard.
Closes #163
- Resolve #163
> feat(admincoupon): create Coupon Card for Admin Dashboard

- package-lock.json
- package.json
- src/pages/admin/coupons.jsx
- src/styles/globals.css
Develop an admin page specifically for managing coupons.
Closes #165
- Resolve #165
> feat(couponsadmin page): create Admin Coupons Page

- src/components/Navbar/index.jsx
- src/components/Profile/index.jsx
Enhance the navbar by adding a user profile section that includes options for displaying user details,
Closes #167
- Resolve #167
> feat(navbar): add User Profile Section to Navbar

- src/components/Banner/index.jsx
- src/components/Email/Email.jsx
- src/components/Email/__test__/__snapshots__/Email.test.js.snap
- src/components/Navbar/index.jsx
- src/components/sponsors/__test__/__snapshots__/sponsor.test.js.snap
- src/components/sponsors/sponsor.jsx
- src/containers/Home/index.jsx
Improve the design of the phone navbar to enhance its usability,
Closes #175
- Resolve #175
> feat(navbar): change Phone Navbar Design

- src/components/Admin/ChangeLogo.jsx
- src/components/Admin/EditOrganization.jsx
- src/components/Admin/__test__/ChangeLogo.test.js
- src/components/Admin/__test__/Chart.test.js
- src/components/Admin/__test__/CouponCard.test.js
- src/components/Admin/__test__/EditOrganization.test.js
- src/components/Admin/__test__/__snapshots__/ChangeLogo.test.js.snap
- src/components/Admin/__test__/__snapshots__/Chart.test.js.snap
- src/components/Admin/__test__/__snapshots__/CouponCard.test.js.snap
- src/components/Admin/__test__/__snapshots__/EditOrganization.test.js.snap
- src/containers/Admin/CouponUsed/__test__/CouponUsed.test.js
- src/containers/Admin/CouponUsed/__test__/__snapshots__/CouponUsed.test.js.snap
- src/containers/Admin/EditCoupons/__test__/EditCoupons.test.js
- src/containers/Admin/EditCoupons/__test__/__snapshots__/EditCoupons.test.js.snap
- src/containers/Admin/EditCoupons/index.jsx
Test the functionalities and components of the admin dashboard page to ensure they work correctly and meet the defined requirements.
Closes #181
- Resolve #181
> test(admin dashboard test): admin Dashboard Page Testing

- src/components/Auth/__test__/Email.test.js
- src/components/Auth/__test__/Signin.test.js
- src/components/Auth/__test__/Signup.test.js
- src/components/Auth/__test__/__snapshots__/Email.test.js.snap
- src/components/Auth/__test__/__snapshots__/Signin.test.js.snap
- src/components/Auth/__test__/__snapshots__/Signup.test.js.snap
Test the individual components within the authentication page to ensure they function correctly
Closes #184
- Resolve #184
> test(auth page): authentication Page Components Testing

- src/components/Cards/AdminCoupon/index.jsx
- src/components/Cards/Line.jsx
- src/components/Cards/__test__/AdminCoupon.test.js
- src/components/Cards/__test__/CheckoutCard.test.js
- src/components/Cards/__test__/CouponCard.test.js
- src/components/Cards/__test__/__snapshots__/AdminCoupon.test.js.snap
- src/components/Cards/__test__/__snapshots__/CheckoutCard.test.js.snap
- src/components/Cards/__test__/__snapshots__/CouponCard.test.js.snap
- src/components/CouponsCard/ __test__/ImpactCard.test.js
- src/components/CouponsCard/ __test__/__snapshots__/ImpactCard.test.js.snap
- src/components/Profile/__test__/Profile.test.js
- src/components/Profile/__test__/__snapshots__/Profile.test.js.snap
- src/containers/Cart/Cartpage/index.jsx
- src/containers/Cart/__test__/Cartpage.test.js
- src/containers/Cart/__test__/__snapshots__/Cartpage.test.js.snap
- src/pages/admin/coupons.jsx
Test the components within the cart page and admin coupons page separately to ensure their functionality
Closes #186
- Resolve #186
> test(cart page): cart & Admin/Coupons Page

- src/components/FeedbackForm/__test__/FeedbackForm.test.js
- src/components/FeedbackForm/__test__/__snapshots__/FeedbackForm.test.js.snap
snapshot test the feedback form component
Closes #191
- Resolve #191
> test(404 page): snapshot test feedback form

- src/components/BlogCard/__test__/BlogCard.test.js
- src/components/BlogCard/__test__/__snapshots__/BlogCard.test.js.snap
> test(test): creating test for the blogcard

- src/components/Footer/__test__/Footer.test.js
- src/components/Footer/__test__/__snapshots__/Footer.test.js.snap
- src/components/Language/__test__/Language.test.js
- src/components/Language/__test__/__snapshots__/Language.test.js.snap
> test(test): test for footer and Language DropDown

- src/components/Banner/__test__/Banner.test.js
- src/components/Banner/__test__/__snapshots__/Banner.test.js.snap
- src/components/RestoBoughtFrom/__test__/RestoBoughtFrom.test.js
- src/components/RestoBoughtFrom/__test__/__snapshots__/RestoBoughtFrom.test.js.snap
> test(test): test for Banner and resto bought from
